all:
	g++ pilha1.c -g -o pilha1
	g++ pilha2.c -g -o pilha2
	g++ fila1.c -g -o fila1
	g++ fila2.c -g -o fila2

pilha:
	g++ pilha1.c -g -o pilha1
	g++ pilha2.c -g -o pilha2

fila:
	g++ fila1.c -g -o fila1
	g++ fila2.c -g -o fila2

clean:
	rm fila1 fila2 pilha1 pilha2
